test variable igz-controls-import-error

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -66,54 +66,54 @@ jobs:
 
           "
 
-  build-docker:
-    name: Build Docker
-    runs-on: ubuntu-latest
-    outputs:
-      igz-controls-import-error: ${{ steps.check-error.outputs.igz-controls-import-error }}
-
-    steps:
-      - name: Exit if merge commit
-        if: github.event.pull_request.merged == true
-        run: |
-          echo "Skipping workflow because this is a merge commit."
-          exit 0
-
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Build Docker image
-        id: build
-        run: |
-          docker build -t my-react-app:$GITHUB_SHA . > build.log 2>&1 || (cat build.log; exit 1)
-
-      - name: Check for igz-controls error message
-        id: check-error
-        if: failure()
-        run: |
-          if grep -q "igz-controls/" build.log; then
-            echo -e "\033[31mModule not found: Error: Can't resolve 'igz-controls....'.\033[0m"
-            echo -e "\033[33mPlease check for changes in the 'dashboard-react-controls' repository.\033[0m"
-            echo "::set-output name=igz-controls-import-error::failure"
-            echo "::error::Module not found: Error: Can't resolve 'igz-controls"
-            echo "${{ toJson(steps) }}"
-
-          else
-            echo "::set-output name=igz-controls-import-error::success"
-            echo "igz-controls-import-error=success" >> $GITHUB_ENV
-          fi
+#  build-docker:
+#    name: Build Docker
+#    runs-on: ubuntu-latest
+#    outputs:
+#      igz-controls-import-error: ${{ steps.check-error.outputs.igz-controls-import-error }}
+#
+#    steps:
+#      - name: Exit if merge commit
+#        if: github.event.pull_request.merged == true
+#        run: |
+#          echo "Skipping workflow because this is a merge commit."
+#          exit 0
+#
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#
+#      - name: Build Docker image
+#        id: build
+#        run: |
+#          docker build -t my-react-app:$GITHUB_SHA . > build.log 2>&1 || (cat build.log; exit 1)
+#
+#      - name: Check for igz-controls error message
+#        id: check-error
+#        if: failure()
+#        run: |
+#          if grep -q "igz-controls/" build.log; then
+#            echo -e "\033[31mModule not found: Error: Can't resolve 'igz-controls....'.\033[0m"
+#            echo -e "\033[33mPlease check for changes in the 'dashboard-react-controls' repository.\033[0m"
+#            echo "::set-output name=igz-controls-import-error::failure"
+#            echo "::error::Module not found: Error: Can't resolve 'igz-controls"
+#            echo "${{ toJson(steps) }}"
+#
+#          else
+#            echo "::set-output name=igz-controls-import-error::success"
+#            echo "igz-controls-import-error=success" >> $GITHUB_ENV
+#          fi
 
   lint-check:
     name: Lint Check
     runs-on: ubuntu-latest
-    needs: build-docker
-    if: failure() && needs.build-docker.outputs.igz-controls-import-error == 'failure'
+#    needs: build-docker
+#    if: failure() && needs.build-docker.outputs.igz-controls-import-error == 'failure'
     steps:
-      - name: Exit if merge commit
-        if: github.event.pull_request.merged == true
-        run: |
-          echo "Skipping workflow because this is a merge commit."
-          exit 0
+#      - name: Exit if merge commit
+#        if: github.event.pull_request.merged == true
+#        run: |
+#          echo "Skipping workflow because this is a merge commit."
+#          exit 0
 
       - name: Checkout code
         uses: actions/checkout@v3
@@ -133,12 +133,12 @@ jobs:
         run: |
           export NODE_ENV=production
           npx eslint 'src/**/*.js' \
-                 --ignore-pattern 'tests/**' \
-                 --ignore-pattern 'src/stories/**' \
-                 --ignore-pattern 'src/**/*.test.js' \
-                 --ignore-pattern 'src/App.test.js' \
-                 --ignore-pattern 'config/**' \
-                 --ignore-pattern 'scripts/*' \
-                 --ignore-pattern '**/__tests__/**' \
-                 --ignore-pattern 'generate-release-notes.js' \
-                 --ignore-pattern '**/*.stories.js'
+#                 --ignore-pattern 'tests/**' \
+#                 --ignore-pattern 'src/stories/**' \
+#                 --ignore-pattern 'src/**/*.test.js' \
+#                 --ignore-pattern 'src/App.test.js' \
+#                 --ignore-pattern 'config/**' \
+#                 --ignore-pattern 'scripts/*' \
+#                 --ignore-pattern '**/__tests__/**' \
+#                 --ignore-pattern 'generate-release-notes.js' \
+#                 --ignore-pattern '**/*.stories.js'
